# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2022 eys3d - All Rights Reserved
# Hammer Hsieh, eys3d Software Engineering, eys3d@eys3d.com

obj-$(CONFIG_VIDEO_eCV5546) += ecv5546_display.o disp_tcon.o disp_dmix.o disp_tgen.o disp_vpp.o disp_osd.o disp_mipitx.o